language: go

go:
  - 1.11.x

# Only clone the most recent commit.
git:
  depth: 1

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  - GO111MODULE=on

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin

script:
  - go test ./...
  - go build ./...

after_success:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel 
