version: '3'
services:
  traces:
    networks:
      - traces
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"

  jaeger:
    image: jaegertracing/all-in-one:1.16
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - traces
networks:
  traces:
    driver: bridge